---
- hosts: all_groups
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: install general packages
        yum: name=wget,mc,net-tools,tmux,telnet,vim,libselinux-python state=present
      - name: install java
        script: /vagrant/bootstrap/install_java.sh
        args:
            creates: /opt/java
- hosts: kafka
  vars:
    kafka_home: /opt/kafka
    kafka_topic_name: jmeter-loader
    kafka_replication_factor: 1
    kafka_partitions_number: 1
    kafka_version: 2.12-0.10.2.0
    kafka_domain: 192.168.33.10
    kafka_port: 9092
    zookeeper_port: 2181
    zookeeper_domain: 192.168.33.10
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: install kafka
        script: "/vagrant/bootstrap/kafka/install_kafka.sh {{kafka_version}} {{kafka_domain}} {{kafka_port}}"
        args:
            creates: /opt/kafka
      - name: copy init scripts to manage kafka and zookeeper servers
        copy: src={{ item.src }} dest={{ item.dest }} mode=751
        with_items:
            - { src: '/vagrant/bootstrap/kafka/kafka', dest: '/etc/init.d/kafka' }
            - { src: '/vagrant/bootstrap/kafka/zookeeper', dest: '/etc/init.d/zookeeper' }
      - name: prepare shutdown runlevel symlinks for zookeeper and kafka
        script: /vagrant/bootstrap/kafka/prepare_shutdown_symlinks.sh
      - name: start zookeeper
        service: name=zookeeper enabled=yes state=started runlevel=0356
      - name: start kafka
        service: name=kafka enabled=yes state=started runlevel=0356
      - name: create topic
        shell: "{{ kafka_home }}/bin/kafka-topics.sh --create --zookeeper {{ zookeeper_domain }}:{{ zookeeper_port }} --replication-factor {{ kafka_replication_factor }} --partitions {{ kafka_partitions_number }} --topic {{ kafka_topic_name }} &"  
- hosts: spark
  vars:
    spark_home: /opt/spark
    spark_domain: localhost
    spark_port: 8080
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: install spark
        script: /vagrant/bootstrap/spark/install_spark.sh
        args:
            creates: /opt/spark
      - name: create spark properties
        template: src=./bootstrap/spark/variables dest=/opt/spark/variables
      - name: run spark
        shell: "source {{ spark_home }}/variables && {{ spark_home }}/sbin/./start-all.sh"
      - name: wait for spark server
        local_action: wait_for host={{ spark_domain }} state=started port={{ spark_port }} delay=20 timeout=300 connect_timeout=15
- hosts: cassandra
  vars:
    cassandra_version: 3.9
    cassandra_cluster_name: cluster-jmeter-loader
    cassandra_cluster_node_number: 3
  remote_user: vagrant
  become: yes
  become_method: sudo
  tasks:
      - name: install git
        yum: name=git state=present
      - name: install python-pip
        yum: name=python-pip state=present
      - name: install PyYAML
        shell: pip install cql PyYAML
      - name: install cassandra cluster manager
        script: /vagrant/bootstrap/cassandra/install_ccm.sh
        args:
            creates: /opt/ccm
      - name: create cassandra cluster
        shell: "ccm create {{ cassandra_cluster_name }} -v {{ cassandra_version }} && touch /opt/ccm/cluster_creation.log > /opt/ccm/cluster_creation.log"
        args:
            creates: "/home/vagrant/.ccm/{{ cassandra_cluster_name }}"
      - name: add nodes to cassandra cluster
        shell: ccm populate --nodes {{ cassandra_cluster_node_number }} && touch /opt/ccm/cluster_population.log > /opt/ccm/cluster_population.log
      - name: start cassandra cluster manager
        shell: ccm start && touch /opt/ccm/start_cluster.log > /opt/ccm/start_cluster.log
      - name: install cqlsh
        shell: pip install cqlsh